/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Esper.Config;
import Events.EastButtonReading;
import Events.NorthButtonReading;
import Events.Power;
import Events.SouthButtonReading;
import Events.WestButtonReading;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author BUE
 */
public class TrafficView extends javax.swing.JFrame {

    /**
     * Creates new form TrafficView
     */
    public TrafficView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EastBtn = new javax.swing.JButton();
        WestBtn = new javax.swing.JButton();
        NorthBtn = new javax.swing.JButton();
        SouthBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NorthLight = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        EastLight = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        WestLight = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        SouthLight = new javax.swing.JTextField();
        Intersection = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OnBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        OffBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TrafficLightStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CarsNorth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CarsWest = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CarsEast = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CarsSouth = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traffic Controller");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EastBtn.setBackground(new java.awt.Color(0, 0, 0));
        EastBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button.png"))); // NOI18N
        EastBtn.setEnabled(false);
        EastBtn.setPreferredSize(new java.awt.Dimension(55, 55));
        EastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EastBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EastBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 60, 50));

        WestBtn.setBackground(new java.awt.Color(0, 0, 0));
        WestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button.png"))); // NOI18N
        WestBtn.setEnabled(false);
        WestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WestBtnActionPerformed(evt);
            }
        });
        getContentPane().add(WestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 60, 50));

        NorthBtn.setBackground(new java.awt.Color(0, 0, 0));
        NorthBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button.png"))); // NOI18N
        NorthBtn.setEnabled(false);
        NorthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorthBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NorthBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 50));

        SouthBtn.setBackground(new java.awt.Color(0, 0, 0));
        SouthBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Button.png"))); // NOI18N
        SouthBtn.setEnabled(false);
        SouthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SouthBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SouthBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 60, 50));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NorthLight.setEditable(false);
        NorthLight.setBackground(new java.awt.Color(255, 0, 0));
        NorthLight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NorthLight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NorthLight.setText("0");
        NorthLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorthLightActionPerformed(evt);
            }
        });
        jPanel2.add(NorthLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, 60));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EastLight.setEditable(false);
        EastLight.setBackground(new java.awt.Color(255, 255, 0));
        EastLight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EastLight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EastLight.setText("0");
        EastLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EastLightActionPerformed(evt);
            }
        });
        jPanel3.add(EastLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 60, 60));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WestLight.setEditable(false);
        WestLight.setBackground(new java.awt.Color(255, 255, 0));
        WestLight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        WestLight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WestLight.setText("0");
        WestLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WestLightActionPerformed(evt);
            }
        });
        jPanel4.add(WestLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 60, 60));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SouthLight.setEditable(false);
        SouthLight.setBackground(new java.awt.Color(255, 0, 0));
        SouthLight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SouthLight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SouthLight.setText("0");
        SouthLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SouthLightActionPerformed(evt);
            }
        });
        jPanel5.add(SouthLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 60, 60));

        Intersection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Intersection.jpg"))); // NOI18N
        getContentPane().add(Intersection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OnBtn.setBackground(new java.awt.Color(0, 255, 47));
        OnBtn.setText("ON");
        OnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnBtnActionPerformed(evt);
            }
        });
        jPanel1.add(OnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Traffic System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        OffBtn.setBackground(new java.awt.Color(255, 0, 0));
        OffBtn.setText("OFF");
        OffBtn.setEnabled(false);
        OffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffBtnActionPerformed(evt);
            }
        });
        jPanel1.add(OffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("System Status");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        TrafficLightStatus.setEditable(false);
        TrafficLightStatus.setBackground(new java.awt.Color(255, 0, 0));
        TrafficLightStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TrafficLightStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TrafficLightStatus.setText("OFF");
        TrafficLightStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrafficLightStatusActionPerformed(evt);
            }
        });
        jPanel1.add(TrafficLightStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 75, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Cars Detector");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        CarsNorth.setEditable(false);
        CarsNorth.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        CarsNorth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CarsNorth.setText("0");
        CarsNorth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarsNorthActionPerformed(evt);
            }
        });
        jPanel1.add(CarsNorth, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 75, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("North");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 240, -1, -1));

        CarsWest.setEditable(false);
        CarsWest.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        CarsWest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CarsWest.setText("0");
        jPanel1.add(CarsWest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 75, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("West");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 310, -1, -1));

        CarsEast.setEditable(false);
        CarsEast.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        CarsEast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CarsEast.setText("0");
        jPanel1.add(CarsEast, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 75, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("East");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("South");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 380, -1, -1));

        CarsSouth.setEditable(false);
        CarsSouth.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        CarsSouth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CarsSouth.setText("0");
        jPanel1.add(CarsSouth, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 75, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 240, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EastBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new EastButtonReading(true));
    }//GEN-LAST:event_EastBtnActionPerformed

    private void OnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new Power(true));
    }//GEN-LAST:event_OnBtnActionPerformed

    private void OffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new Power(false));
    }//GEN-LAST:event_OffBtnActionPerformed

    private void TrafficLightStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrafficLightStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrafficLightStatusActionPerformed

    private void WestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WestBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new WestButtonReading(true));
    }//GEN-LAST:event_WestBtnActionPerformed

    private void SouthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SouthBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new SouthButtonReading(true));
    }//GEN-LAST:event_SouthBtnActionPerformed

    private void NorthLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorthLightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NorthLightActionPerformed

    private void NorthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorthBtnActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new NorthButtonReading(true));
    }//GEN-LAST:event_NorthBtnActionPerformed

    private void EastLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EastLightActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EastLightActionPerformed

    private void WestLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WestLightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WestLightActionPerformed

    private void SouthLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SouthLightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SouthLightActionPerformed

    private void CarsNorthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarsNorthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarsNorthActionPerformed

    public JButton getOffBtn() {
        return OffBtn;
    }

    public JButton getOnBtn() {
        return OnBtn;
    }

    public JTextField getTrafficLightStatus() {
        return TrafficLightStatus;
    }

    public JTextField getCarsEast() {
        return CarsEast;
    }

    public JTextField getCarsNorth() {
        return CarsNorth;
    }

    public JTextField getCarsSouth() {
        return CarsSouth;
    }

    public JTextField getCarsWest() {
        return CarsWest;
    }

    public JButton getEastBtn() {
        return EastBtn;
    }

    public JButton getNorthBtn() {
        return NorthBtn;
    }

    public JButton getSouthBtn() {
        return SouthBtn;
    }

    public JButton getWestBtn() {
        return WestBtn;
    }




    public JTextField getEastLight() {
        return EastLight;
    }

    public JTextField getNorthLight() {
        return NorthLight;
    }

    public JTextField getSouthLight() {
        return SouthLight;
    }

    public JTextField getWestLight() {
        return WestLight;
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrafficView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrafficView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrafficView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrafficView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrafficView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CarsEast;
    private javax.swing.JTextField CarsNorth;
    private javax.swing.JTextField CarsSouth;
    private javax.swing.JTextField CarsWest;
    private javax.swing.JButton EastBtn;
    private javax.swing.JTextField EastLight;
    private javax.swing.JLabel Intersection;
    private javax.swing.JButton NorthBtn;
    private javax.swing.JTextField NorthLight;
    private javax.swing.JButton OffBtn;
    private javax.swing.JButton OnBtn;
    private javax.swing.JButton SouthBtn;
    private javax.swing.JTextField SouthLight;
    private javax.swing.JTextField TrafficLightStatus;
    private javax.swing.JButton WestBtn;
    private javax.swing.JTextField WestLight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
